name: deploySingleVM

on: [workflow_dispatch]

permissions: 
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{secrets.CREDS}}
          # CREDS looks like this:
          # {
          #   "tenantId": "<GUID>",
          #   "subscriptionId": "<GUID>",
          #   "clientId": "<GUID>",
          #   "clientSecret": "<GUID>"
          # }
      - uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./IaC/bicep/orchestration/singleVM/singleVM.bicep
          parameters: IaC/bicep/orchestration/singleVM/singleVMParameters.json